query SalesRepOrders($organizationId: String, $storeId: String, $cultureName: String, $first: Int, $sort: String) {
  salesRepOrders(
    organizationId: $organizationId
    storeId: $storeId
    cultureName: $cultureName
    first: $first
    sort: $sort
  ) {
    totalCount
    items {
      id
      number
      organizationId
      organizationName
      createdDate
      status
      statusDisplayValue
      itemsCount
      total {
        amount
        formattedAmount
        currency {
          code
          symbol
        }
      }
    }
  }
}
