query SalesRepOrders($organizationId: String, $storeId: String, $statuses: [String], $first: Int, $sort: String) {
  salesRepOrders(organizationId: $organizationId, storeId: $storeId, statuses: $statuses, first: $first, sort: $sort) {
    totalCount
    items {
      id
      number
      organizationId
      organizationName
      createdDate
      status
      statusDisplayValue
      itemsCount
      total {
        amount
        formattedAmount
        currency {
          code
          symbol
        }
      }
    }
  }
}
