export const DEFAULT_DEBOUNCE_IN_MS = 300;
export const EXTENDED_DEBOUNCE_IN_MS = 1000;

export const QUANTITY_VALIDATION_ERROR_CODES: ReadonlySet<string> = new Set([
  "PRODUCT_QTY_CHANGED",
  "PRODUCT_MIN_QTY",
  "PRODUCT_MAX_QTY",
  "PRODUCT_MIN_MAX_QTY",
  "PRODUCT_QTY_INSUFFICIENT",
  "PRODUCT_MIN_QTY_NOT_AVAILABLE",
  "PRODUCT_EXACT_QTY",
]);
