query GetOrganizationContacts(
  $id: String!
  $userId: String!
  $first: Int
  $after: String
  $sort: String
  $searchPhrase: String
  $roleIds: [String]
  $statuses: [String]
) {
  organization(id: $id, userId: $userId) {
    contacts(
      first: $first
      after: $after
      sort: $sort
      searchPhrase: $searchPhrase
      roleIds: $roleIds
      statuses: $statuses
    ) {
      items {
        id
        name
        firstName
        lastName
        fullName
        emails
        status
        statusInOrganization
        isLockedInOrganization
        rolesInOrganization {
          id
          name
        }
        securityAccounts {
          id
          email
          roles {
            id
            name
          }
        }
      }
      totalCount
    }
  }
}
