query SalesRepDocuments(
  $first: Int
  $after: String
  $keyword: String
  $sort: String
  $category: String
  $pinned: Boolean
) {
  salesRepDocuments(
    first: $first
    after: $after
    keyword: $keyword
    sort: $sort
    category: $category
    pinned: $pinned
  ) {
    totalCount
    items {
      id
      name
      displayName
      category
      isPinned
      contentType
      size
      createdDate
      modifiedDate
      url
      summary
      pageCount
      previewUrl
    }
  }
}
