query GetReturns(
  $storeId: String!
  $scope: ReturnScopeEnum
  $first: Int
  $after: String
  $sort: String
  $keyword: String
  $statuses: [String]
  $startDate: DateTime
  $endDate: DateTime
  $cultureName: String
) {
  returns(
    storeId: $storeId
    scope: $scope
    first: $first
    after: $after
    sort: $sort
    keyword: $keyword
    statuses: $statuses
    startDate: $startDate
    endDate: $endDate
  ) {
    totalCount
    items {
      id
      number
      status
      statusDisplayValue(cultureName: $cultureName)
      createdDate
      orderId
      customerName
      itemsQuantity
      availableActions {
        name
        isAvailable
        unavailableReason
      }
    }
  }
}
