export const FETCH_CART="fetchCart";
export const FETCH_CART_ITEMS_COUNT = "fetchCartItemsCount";
export const ADD_ITEM_TO_CART="addItemToCart";
export const DELETE_ITEM_FROM_CART="deleteItemFromCart";
export const CLEAR_CART =  "clearCart";
export const CHANGE_ITEM_QUANTITY = "changeCartItemQuantity";
export const SHOW_CART_SIDEBAR = "showCartSidebar";
export const HIDE_CART_SIDEBAR = "hideCartSidebar";
export const CHECKOUT = "checkout";
