// AUTO-GENERATED by client-app/core-api/build-types.mjs — DO NOT EDIT.
// Self-contained public type contract of @vc-frontend/core.
// Regenerate with: yarn build:core-types

import * as vue from 'vue';
import { Component } from 'vue';
import { RouteLocationRaw, Router } from 'vue-router';
import * as _apollo_client_cache from '@apollo/client/cache';
import { ApolloClient } from '@apollo/client/core';
import * as _vueuse_core from '@vueuse/core';
import * as vue_i18n from 'vue-i18n';
import { IntlNumberFormat } from 'vue-i18n';
import { LocaleMessage } from '@intlify/core-base';

interface IProps$2 {
    src: string;
}
declare const __VLS_export$2: vue.DefineComponent<IProps$2, {}, {}, {}, {}, vue.ComponentOptionsMixin, vue.ComponentOptionsMixin, {}, string, vue.PublicProps, Readonly<IProps$2> & Readonly<{}>, {}, {}, {}, {}, string, vue.ComponentProvideOptions, false, {}, any>;
declare const _default$2: typeof __VLS_export$2;

type Maybe<T> = T;
/** All built-in and custom scalars, mapped to their actual values */
type Scalars = {
    ID: {
        input: string;
        output: string;
    };
    String: {
        input: string;
        output: string;
    };
    Boolean: {
        input: boolean;
        output: boolean;
    };
    Int: {
        input: number;
        output: number;
    };
    Float: {
        input: number;
        output: number;
    };
    /** The `Date` scalar type represents a year, month and day in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard. */
    Date: {
        input: string;
        output: string;
    };
    /** The `DateTime` scalar type represents a date and time. `DateTime` expects timestamps to be formatted in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard. */
    DateTime: {
        input: any;
        output: any;
    };
    Decimal: {
        input: number;
        output: number;
    };
    DynamicPropertyValue: {
        input: string | number | boolean | null;
        output: string | number | boolean | null;
    };
    Long: {
        input: number;
        output: number;
    };
    ModuleSettingValue: {
        input: string | number | boolean | null;
        output: string | number | boolean | null;
    };
    OptionalDecimal: {
        input: number | undefined;
        output: number | undefined;
    };
    OptionalNullableDecimal: {
        input: number | null | undefined;
        output: number | null | undefined;
    };
    OptionalString: {
        input: string | undefined;
        output: string | undefined;
    };
    PropertyValue: {
        input: string | number | boolean | null;
        output: string | number | boolean | null;
    };
    /** The `Seconds` scalar type represents a period of time represented as the total number of seconds in range [-922337203685, 922337203685]. */
    Seconds: {
        input: number;
        output: number;
    };
    /** Asset URL string. When the store defines an asset public URL, the value is resolved against it. */
    StoreAssetUrl: {
        input: any;
        output: any;
    };
};
type Asset = {
    /** Culture name */
    cultureName?: Maybe<Scalars['String']['output']>;
    /** The description of the asset. */
    description?: Maybe<Scalars['String']['output']>;
    /** The group of the asset. */
    group?: Maybe<Scalars['String']['output']>;
    /** The unique ID of the asset. */
    id: Scalars['String']['output'];
    /** The MIME type of the asset. */
    mimeType?: Maybe<Scalars['String']['output']>;
    /** The name of the asset. */
    name?: Maybe<Scalars['String']['output']>;
    /** The relative URL of the asset. */
    relativeUrl?: Maybe<Scalars['String']['output']>;
    /** The size of the asset in bytes. */
    size: Scalars['Long']['output'];
    /** The type ID of the asset. */
    typeId: Scalars['String']['output'];
    /** The URL of the asset. */
    url: Scalars['StoreAssetUrl']['output'];
};
type AvailabilityData = {
    /** Available quantity */
    availableQuantity: Scalars['Long']['output'];
    /** Inventories */
    inventories: Array<InventoryInfo>;
    /** Is active */
    isActive: Scalars['Boolean']['output'];
    /** Is available */
    isAvailable: Scalars['Boolean']['output'];
    /** Is buyable */
    isBuyable: Scalars['Boolean']['output'];
    /** Is estimated */
    isEstimated: Scalars['Boolean']['output'];
    /** Is in stock */
    isInStock: Scalars['Boolean']['output'];
    /** Is track inventory */
    isTrackInventory: Scalars['Boolean']['output'];
};
type BrandType = {
    bannerUrl?: Maybe<Scalars['StoreAssetUrl']['output']>;
    /** Brand property name. */
    brandPropertyName?: Maybe<Scalars['String']['output']>;
    /** Unlocalized brand name. */
    brandPropertyValue?: Maybe<Scalars['String']['output']>;
    description?: Maybe<Scalars['String']['output']>;
    /** Indicates if the brand is featured. */
    featured?: Maybe<Scalars['Boolean']['output']>;
    /** Brand ID. */
    id: Scalars['String']['output'];
    logoUrl?: Maybe<Scalars['StoreAssetUrl']['output']>;
    /** Brand name. */
    name?: Maybe<Scalars['String']['output']>;
    permalink: Scalars['String']['output'];
};
type Breadcrumb = {
    /** Id of item the breadcrumb calculated for */
    itemId: Scalars['String']['output'];
    /** Semantic URL keyword */
    semanticUrl?: Maybe<Scalars['String']['output']>;
    /** Full path from catalog */
    seoPath?: Maybe<Scalars['String']['output']>;
    /** Name of current breadcrumb */
    title: Scalars['String']['output'];
    /** Catalog, category or product */
    typeName: Scalars['String']['output'];
};
type CatalogDiscountType = {
    /** Discount amount */
    amount: Scalars['Decimal']['output'];
    /** Discount amount with tax */
    amountWithTax: Scalars['Decimal']['output'];
    /** Coupon */
    coupon?: Maybe<Scalars['String']['output']>;
    /** Value of discount description */
    description?: Maybe<Scalars['String']['output']>;
    /** Discount amount in the specified currency */
    moneyAmount: MoneyType;
    /** Discount amount with tax in the specified currency */
    moneyAmountWithTax: MoneyType;
    promotion?: Maybe<Promotion>;
    /** Value of promotion id */
    promotionId?: Maybe<Scalars['String']['output']>;
};
type Category = {
    /** Assets */
    assets: Array<Asset>;
    /** Breadcrumbs */
    breadcrumbs: Array<Breadcrumb>;
    childCategories: Array<Category>;
    /** SKU of category. */
    code: Scalars['String']['output'];
    description?: Maybe<CategoryDescriptionType>;
    descriptions: Array<CategoryDescriptionType>;
    /** Have a parent */
    hasParent: Scalars['Boolean']['output'];
    /** Id of category. */
    id: Scalars['String']['output'];
    /** Images */
    images: Array<ImageType>;
    /** The category image. */
    imgSrc?: Maybe<Scalars['StoreAssetUrl']['output']>;
    /** Level in hierarchy */
    level: Scalars['Int']['output'];
    /** The name of the category. */
    name: Scalars['String']['output'];
    /** All parent categories ids relative to the requested catalog and concatenated with \ . E.g. (1/21/344) */
    outline?: Maybe<Scalars['String']['output']>;
    /** Outlines */
    outlines: Array<OutlineType>;
    parent?: Maybe<Category>;
    /** Category path in to the requested catalog  (all parent categories names concatenated. E.g. (parent1/parent2)) */
    path?: Maybe<Scalars['String']['output']>;
    /** The category priority. */
    priority: Scalars['Int']['output'];
    properties: Array<Property>;
    /** Category relevance score */
    relevanceScore?: Maybe<Scalars['Float']['output']>;
    /** Request related SEO info */
    seoInfo: SeoInfo;
    /** Request related slug for category */
    slug?: Maybe<Scalars['String']['output']>;
};
type CategoryDescriptionType = {
    /** Description text. */
    content?: Maybe<Scalars['String']['output']>;
    /** Description type. */
    descriptionType?: Maybe<Scalars['String']['output']>;
    /** Description ID. */
    id: Scalars['String']['output'];
    /** Description language code. */
    languageCode?: Maybe<Scalars['String']['output']>;
};
type CommonVendor = {
    /** Vendor ID */
    id: Scalars['String']['output'];
    /** Vendor name */
    name: Scalars['String']['output'];
    /** Vendor rating */
    rating?: Maybe<Rating>;
};
type CurrencyType = {
    /** Currency code may be used ISO 4217 */
    code: Scalars['String']['output'];
    /** Currency culture name */
    cultureName: Scalars['String']['output'];
    /** Currency custom formatting */
    customFormatting?: Maybe<Scalars['String']['output']>;
    /** Currency english name */
    englishName: Scalars['String']['output'];
    /** Exchange rate */
    exchangeRate: Scalars['Decimal']['output'];
    /** Currency name */
    name: Scalars['String']['output'];
    /** Symbol */
    symbol: Scalars['String']['output'];
};
type CustomerOrderType = {
    addresses: Array<OrderAddressType>;
    /** Available payment methods */
    availablePaymentMethods: Array<OrderPaymentMethodType>;
    cancelReason?: Maybe<Scalars['String']['output']>;
    cancelledDate?: Maybe<Scalars['DateTime']['output']>;
    channelId?: Maybe<Scalars['String']['output']>;
    comment?: Maybe<Scalars['String']['output']>;
    coupons: Array<Scalars['String']['output']>;
    createdBy?: Maybe<Scalars['String']['output']>;
    createdDate: Scalars['DateTime']['output'];
    currency: CurrencyType;
    customerId: Scalars['String']['output'];
    customerName?: Maybe<Scalars['String']['output']>;
    discountAmount: MoneyType;
    discountTotal: MoneyType;
    discountTotalWithTax: MoneyType;
    discounts: Array<OrderDiscountType>;
    /** Customer order dynamic property values */
    dynamicProperties: Array<DynamicPropertyValueType>;
    employeeId?: Maybe<Scalars['String']['output']>;
    employeeName?: Maybe<Scalars['String']['output']>;
    fee: MoneyType;
    feeTotal: MoneyType;
    feeTotalWithTax: MoneyType;
    feeWithTax: MoneyType;
    id: Scalars['String']['output'];
    inPayments: Array<PaymentInType>;
    isApproved: Scalars['Boolean']['output'];
    isCancelled: Scalars['Boolean']['output'];
    isPrototype: Scalars['Boolean']['output'];
    items: Array<OrderLineItemType>;
    languageCode?: Maybe<Scalars['String']['output']>;
    modifiedBy?: Maybe<Scalars['String']['output']>;
    modifiedDate?: Maybe<Scalars['DateTime']['output']>;
    number: Scalars['String']['output'];
    objectType: Scalars['String']['output'];
    operationType: Scalars['String']['output'];
    /** Order totals */
    orderTotals?: Maybe<Array<Maybe<OrderTotalType>>>;
    organizationId?: Maybe<Scalars['String']['output']>;
    organizationName?: Maybe<Scalars['String']['output']>;
    outerId?: Maybe<Scalars['String']['output']>;
    parentOperationId?: Maybe<Scalars['String']['output']>;
    paymentDiscountTotal: MoneyType;
    paymentDiscountTotalWithTax: MoneyType;
    paymentSubTotal: MoneyType;
    paymentSubTotalWithTax: MoneyType;
    paymentTaxTotal: MoneyType;
    paymentTotal: MoneyType;
    paymentTotalWithTax: MoneyType;
    purchaseOrderNumber?: Maybe<Scalars['String']['output']>;
    shipments: Array<OrderShipmentType>;
    shippingDiscountTotal: MoneyType;
    shippingDiscountTotalWithTax: MoneyType;
    shippingSubTotal: MoneyType;
    shippingSubTotalWithTax: MoneyType;
    shippingTaxTotal: MoneyType;
    shippingTotal: MoneyType;
    shippingTotalWithTax: MoneyType;
    shoppingCartId?: Maybe<Scalars['String']['output']>;
    status?: Maybe<Scalars['String']['output']>;
    statusDisplayValue?: Maybe<Scalars['String']['output']>;
    storeId: Scalars['String']['output'];
    storeName?: Maybe<Scalars['String']['output']>;
    subTotal: MoneyType;
    subTotalDiscount: MoneyType;
    subTotalDiscountWithTax: MoneyType;
    subTotalTaxTotal: MoneyType;
    subTotalWithTax: MoneyType;
    subscriptionId?: Maybe<Scalars['String']['output']>;
    subscriptionNumber?: Maybe<Scalars['String']['output']>;
    taxDetails: Array<OrderTaxDetailType>;
    taxPercentRate: Scalars['Decimal']['output'];
    taxTotal: MoneyType;
    taxType?: Maybe<Scalars['String']['output']>;
    total: MoneyType;
};
type DescriptionType = {
    /** Description text. */
    content?: Maybe<Scalars['String']['output']>;
    /** Description ID. */
    id: Scalars['String']['output'];
    /** Description language code. */
    languageCode?: Maybe<Scalars['String']['output']>;
    /** Description type. */
    reviewType?: Maybe<Scalars['String']['output']>;
};
/** A connection from an object to a list of objects of type `DictionaryItem`. */
type DictionaryItemConnection = {
    /** A list of all of the edges returned in the connection. */
    edges?: Maybe<Array<Maybe<DictionaryItemEdge>>>;
    /** A list of all of the objects returned in the connection. This is a convenience field provided for quickly exploring the API; rather than querying for "{ edges { node } }" when no edge data is needed, this field can be used instead. Note that when clients like Relay need to fetch the "cursor" field on the edge to enable efficient pagination, this shortcut cannot be used, and the full "{ edges { node } } " version should be used instead. */
    items?: Maybe<Array<Maybe<DictionaryItemType>>>;
    /** Information to aid in pagination. */
    pageInfo: PageInfo;
    /** A count of the total number of objects in this connection, ignoring pagination. This allows a client to fetch the first five objects by passing "5" as the argument to `first`, then fetch the total count so it could display "5 of 83", for example. In cases where we employ infinite scrolling or don't have an exact count of entries, this field will return `null`. */
    totalCount?: Maybe<Scalars['Int']['output']>;
};
/** An edge in a connection from an object to another object of type `DictionaryItem`. */
type DictionaryItemEdge = {
    /** A cursor for use in pagination */
    cursor: Scalars['String']['output'];
    /** The item at the end of the edge */
    node?: Maybe<DictionaryItemType>;
};
type DictionaryItemType = {
    /** Id */
    id: Scalars['String']['output'];
    /** Localized dictionary item value */
    label?: Maybe<Scalars['String']['output']>;
    /** Name */
    name: Scalars['String']['output'];
};
type DynamicPropertyType = {
    dictionaryItems?: Maybe<DictionaryItemConnection>;
    /** The order for the dynamic property to display */
    displayOrder?: Maybe<Scalars['Int']['output']>;
    /** Value type */
    dynamicPropertyValueType: DynamicPropertyValueTypes;
    /** Id */
    id: Scalars['String']['output'];
    /** Is dynamic property value an array */
    isArray: Scalars['Boolean']['output'];
    /** Is dynamic property value a dictionary */
    isDictionary: Scalars['Boolean']['output'];
    /** Is dynamic property value multilingual */
    isMultilingual: Scalars['Boolean']['output'];
    /** Is dynamic property value required */
    isRequired: Scalars['Boolean']['output'];
    /** Localized property name */
    label?: Maybe<Scalars['String']['output']>;
    name: Scalars['String']['output'];
    /** Object type */
    objectType: Scalars['String']['output'];
};
type DynamicPropertyValueType = {
    /** Associated dictionary item */
    dictionaryItem?: Maybe<DictionaryItemType>;
    /** Associated dynamic property */
    dynamicProperty?: Maybe<DynamicPropertyType>;
    /** Value type */
    dynamicPropertyValueType: DynamicPropertyValueTypes;
    /** Property name */
    name?: Maybe<Scalars['String']['output']>;
    /** Property value */
    value?: Maybe<Scalars['DynamicPropertyValue']['output']>;
    /** Value type */
    valueType: Scalars['String']['output'];
};
/** Dynamic property value type */
declare enum DynamicPropertyValueTypes {
    Boolean = "BOOLEAN",
    DateTime = "DATE_TIME",
    Decimal = "DECIMAL",
    Html = "HTML",
    Image = "IMAGE",
    Integer = "INTEGER",
    LongText = "LONG_TEXT",
    ShortText = "SHORT_TEXT",
    Undefined = "UNDEFINED"
}
type ImageType = {
    /** Culture name */
    cultureName?: Maybe<Scalars['String']['output']>;
    /** The description of the image */
    description?: Maybe<Scalars['String']['output']>;
    /** The group of the image */
    group?: Maybe<Scalars['String']['output']>;
    /** The unique ID of the image */
    id: Scalars['String']['output'];
    /** The name of the image */
    name?: Maybe<Scalars['String']['output']>;
    /** The relative URL of the image */
    relativeUrl?: Maybe<Scalars['String']['output']>;
    /** Sort order */
    sortOrder: Scalars['Int']['output'];
    /** The URL of the image */
    url: Scalars['StoreAssetUrl']['output'];
};
type InventoryInfo = {
    /** Allow backorder */
    allowBackorder: Scalars['Boolean']['output'];
    /** Allow preorder */
    allowPreorder: Scalars['Boolean']['output'];
    /** Backorder availability date */
    backorderAvailabilityDate?: Maybe<Scalars['DateTime']['output']>;
    fulfillmentCenterId: Scalars['String']['output'];
    fulfillmentCenterName: Scalars['String']['output'];
    /** Inventory in stock quantity */
    inStockQuantity: Scalars['Long']['output'];
    /** Preorder availability date */
    preorderAvailabilityDate?: Maybe<Scalars['DateTime']['output']>;
    /** Inventory reserved quantity */
    reservedQuantity: Scalars['Long']['output'];
};
type MoneyType = {
    /** A decimal with the amount rounded to the significant number of decimal digits. */
    amount: Scalars['Decimal']['output'];
    /** Currency type */
    currency: CurrencyType;
    /** Number of decimal digits for the associated currency. */
    decimalDigits: Scalars['Int']['output'];
    /** Formatted amount. */
    formattedAmount: Scalars['String']['output'];
    /** Formatted amount without currency. */
    formattedAmountWithoutCurrency: Scalars['String']['output'];
    /** Formatted amount without point. */
    formattedAmountWithoutPoint: Scalars['String']['output'];
    /** Formatted amount without point and currency. */
    formattedAmountWithoutPointAndCurrency: Scalars['String']['output'];
};
type OrderAddressType = {
    /** Address type */
    addressType?: Maybe<Scalars['Int']['output']>;
    /** City */
    city?: Maybe<Scalars['String']['output']>;
    /** Country code */
    countryCode?: Maybe<Scalars['String']['output']>;
    /** Country name */
    countryName?: Maybe<Scalars['String']['output']>;
    /** Email */
    email?: Maybe<Scalars['String']['output']>;
    /** First name */
    firstName?: Maybe<Scalars['String']['output']>;
    /** Id */
    id?: Maybe<Scalars['String']['output']>;
    /** Id */
    key?: Maybe<Scalars['String']['output']>;
    /** Last name */
    lastName?: Maybe<Scalars['String']['output']>;
    /** Line1 */
    line1?: Maybe<Scalars['String']['output']>;
    /** Line2 */
    line2?: Maybe<Scalars['String']['output']>;
    /** Middle name */
    middleName?: Maybe<Scalars['String']['output']>;
    /** Name */
    name?: Maybe<Scalars['String']['output']>;
    /** Company name */
    organization?: Maybe<Scalars['String']['output']>;
    /** Outer id */
    outerId?: Maybe<Scalars['String']['output']>;
    /** Phone */
    phone?: Maybe<Scalars['String']['output']>;
    /** Postal code */
    postalCode: Scalars['String']['output'];
    /** Region id */
    regionId?: Maybe<Scalars['String']['output']>;
    /** Region name */
    regionName?: Maybe<Scalars['String']['output']>;
    /** Zip */
    zip?: Maybe<Scalars['String']['output']>;
};
type OrderConfigurationItemFileType = {
    /** MIME type of the file */
    contentType?: Maybe<Scalars['String']['output']>;
    /** Name of the file */
    name: Scalars['String']['output'];
    /** Size of the file */
    size: Scalars['Long']['output'];
    /** URL of the file */
    url: Scalars['String']['output'];
};
type OrderConfigurationItemType = {
    /** Custom text for 'Text' configuration item section */
    customText?: Maybe<Scalars['String']['output']>;
    /** Extended price */
    extendedPrice: MoneyType;
    /** List of files for 'File' configuration item section */
    files?: Maybe<Array<Maybe<OrderConfigurationItemFileType>>>;
    /** Configuration item ID */
    id: Scalars['String']['output'];
    /** Configuration item image URL */
    imageUrl?: Maybe<Scalars['String']['output']>;
    /** Configuration item name */
    name?: Maybe<Scalars['String']['output']>;
    /** List price */
    price: MoneyType;
    product?: Maybe<Product>;
    /** Configuration item product ID */
    productId?: Maybe<Scalars['String']['output']>;
    /** Configuration item product quantity */
    quantity?: Maybe<Scalars['Int']['output']>;
    /** Sale price */
    salePrice: MoneyType;
    /** Configuration item section ID */
    sectionId: Scalars['String']['output'];
    /** Configuration item section name */
    sectionName?: Maybe<Scalars['String']['output']>;
    /** Configuration item SKU */
    sku?: Maybe<Scalars['String']['output']>;
    /** Configuration item type. Possible values: 'Product', 'Variation', 'Text', 'File' */
    type: Scalars['String']['output'];
};
type OrderDiscountType = {
    /** Order discount amount */
    amount: MoneyType;
    coupon?: Maybe<Scalars['String']['output']>;
    /** @deprecated Use the new PromotionDescription field instead */
    description?: Maybe<Scalars['String']['output']>;
    /** Description of the promotion */
    promotionDescription?: Maybe<Scalars['String']['output']>;
    promotionId?: Maybe<Scalars['String']['output']>;
    /** Name of the promotion */
    promotionName?: Maybe<Scalars['String']['output']>;
};
type OrderLineItemType = {
    cancelReason?: Maybe<Scalars['String']['output']>;
    cancelledDate?: Maybe<Scalars['DateTime']['output']>;
    catalogId: Scalars['String']['output'];
    categoryId?: Maybe<Scalars['String']['output']>;
    comment?: Maybe<Scalars['String']['output']>;
    /** Configuration items for configurable product */
    configurationItems?: Maybe<Array<Maybe<OrderConfigurationItemType>>>;
    currency: CurrencyType;
    discountAmount: MoneyType;
    discountAmountWithTax: MoneyType;
    discountTotal: MoneyType;
    discountTotalWithTax: MoneyType;
    discounts: Array<OrderDiscountType>;
    /** Customer order Line item dynamic property values */
    dynamicProperties: Array<DynamicPropertyValueType>;
    extendedPrice: MoneyType;
    extendedPriceWithTax: MoneyType;
    fulfillmentCenterId?: Maybe<Scalars['String']['output']>;
    fulfillmentCenterName?: Maybe<Scalars['String']['output']>;
    fulfillmentLocationCode?: Maybe<Scalars['String']['output']>;
    height?: Maybe<Scalars['Decimal']['output']>;
    id: Scalars['String']['output'];
    imageUrl?: Maybe<Scalars['String']['output']>;
    isCancelled: Scalars['Boolean']['output'];
    isGift?: Maybe<Scalars['Boolean']['output']>;
    length?: Maybe<Scalars['Decimal']['output']>;
    listTotal: MoneyType;
    listTotalWithTax: MoneyType;
    measureUnit?: Maybe<Scalars['String']['output']>;
    name: Scalars['String']['output'];
    objectType: Scalars['String']['output'];
    outerId?: Maybe<Scalars['String']['output']>;
    placedPrice: MoneyType;
    placedPriceWithTax: MoneyType;
    price: MoneyType;
    priceId?: Maybe<Scalars['String']['output']>;
    priceWithTax: MoneyType;
    product?: Maybe<Product>;
    productId: Scalars['String']['output'];
    productOuterId?: Maybe<Scalars['String']['output']>;
    productType?: Maybe<Scalars['String']['output']>;
    quantity: Scalars['Int']['output'];
    reserveQuantity: Scalars['Int']['output'];
    shippingMethodCode?: Maybe<Scalars['String']['output']>;
    /** Indicates whether the PlacedPrice should be visible to the customer */
    showPlacedPrice: Scalars['Boolean']['output'];
    sku: Scalars['String']['output'];
    status?: Maybe<Scalars['String']['output']>;
    statusDisplayValue?: Maybe<Scalars['String']['output']>;
    taxDetails: Array<OrderTaxDetailType>;
    taxPercentRate: Scalars['Decimal']['output'];
    taxTotal: MoneyType;
    taxType?: Maybe<Scalars['String']['output']>;
    vendor?: Maybe<CommonVendor>;
    weight?: Maybe<Scalars['Decimal']['output']>;
    weightUnit?: Maybe<Scalars['String']['output']>;
    width?: Maybe<Scalars['Decimal']['output']>;
};
type OrderPaymentMethodType = {
    code: Scalars['String']['output'];
    currency: CurrencyType;
    description?: Maybe<Scalars['String']['output']>;
    discountAmount: MoneyType;
    discountAmountWithTax: MoneyType;
    isActive: Scalars['Boolean']['output'];
    isAvailableForPartial: Scalars['Boolean']['output'];
    logoUrl?: Maybe<Scalars['String']['output']>;
    /** Localized name of payment method. */
    name?: Maybe<Scalars['String']['output']>;
    paymentMethodGroupType: Scalars['Int']['output'];
    paymentMethodType: Scalars['Int']['output'];
    price: MoneyType;
    priceWithTax: MoneyType;
    priority: Scalars['Int']['output'];
    storeId?: Maybe<Scalars['String']['output']>;
    taxDetails?: Maybe<Array<OrderTaxDetailType>>;
    taxPercentRate: Scalars['Decimal']['output'];
    taxTotal: MoneyType;
    taxType?: Maybe<Scalars['String']['output']>;
    total: MoneyType;
    totalWithTax: MoneyType;
    typeName: Scalars['String']['output'];
};
type OrderShipmentItemType = {
    barCode?: Maybe<Scalars['String']['output']>;
    id: Scalars['String']['output'];
    lineItem?: Maybe<OrderLineItemType>;
    lineItemId?: Maybe<Scalars['String']['output']>;
    outerId?: Maybe<Scalars['String']['output']>;
    quantity: Scalars['Int']['output'];
    status?: Maybe<Scalars['String']['output']>;
};
type OrderShipmentPackageType = {
    barCode?: Maybe<Scalars['String']['output']>;
    height?: Maybe<Scalars['Decimal']['output']>;
    id: Scalars['String']['output'];
    items: Array<OrderShipmentItemType>;
    length?: Maybe<Scalars['Decimal']['output']>;
    measureUnit?: Maybe<Scalars['String']['output']>;
    packageType?: Maybe<Scalars['String']['output']>;
    weight?: Maybe<Scalars['Decimal']['output']>;
    weightUnit?: Maybe<Scalars['String']['output']>;
    width?: Maybe<Scalars['Decimal']['output']>;
};
type OrderShipmentType = {
    cancelReason?: Maybe<Scalars['String']['output']>;
    cancelledDate?: Maybe<Scalars['DateTime']['output']>;
    comment?: Maybe<Scalars['String']['output']>;
    currency: CurrencyType;
    customerOrderId?: Maybe<Scalars['String']['output']>;
    deliveryAddress?: Maybe<OrderAddressType>;
    deliveryDate?: Maybe<Scalars['DateTime']['output']>;
    discountAmount: MoneyType;
    discountAmountWithTax: MoneyType;
    discounts: Array<OrderDiscountType>;
    /** Customer order Shipment dynamic property values */
    dynamicProperties: Array<DynamicPropertyValueType>;
    employeeId?: Maybe<Scalars['String']['output']>;
    employeeName?: Maybe<Scalars['String']['output']>;
    fee: MoneyType;
    feeWithTax: MoneyType;
    fulfillmentCenterId?: Maybe<Scalars['String']['output']>;
    fulfillmentCenterName?: Maybe<Scalars['String']['output']>;
    height?: Maybe<Scalars['Decimal']['output']>;
    id: Scalars['String']['output'];
    inPayments: Array<PaymentInType>;
    isApproved: Scalars['Boolean']['output'];
    isCancelled: Scalars['Boolean']['output'];
    items: Array<OrderShipmentItemType>;
    length?: Maybe<Scalars['Decimal']['output']>;
    measureUnit?: Maybe<Scalars['String']['output']>;
    number: Scalars['String']['output'];
    objectType: Scalars['String']['output'];
    operationType: Scalars['String']['output'];
    organizationId?: Maybe<Scalars['String']['output']>;
    organizationName?: Maybe<Scalars['String']['output']>;
    outerId?: Maybe<Scalars['String']['output']>;
    packages: Array<OrderShipmentPackageType>;
    parentOperationId?: Maybe<Scalars['String']['output']>;
    pickupLocation?: Maybe<PickupLocationType>;
    price: MoneyType;
    priceWithTax: MoneyType;
    shipmentMethodCode?: Maybe<Scalars['String']['output']>;
    shipmentMethodOption?: Maybe<Scalars['String']['output']>;
    shippingMethod?: Maybe<OrderShippingMethodType>;
    status?: Maybe<Scalars['String']['output']>;
    statusDisplayValue?: Maybe<Scalars['String']['output']>;
    taxDetails: Array<OrderTaxDetailType>;
    taxPercentRate: Scalars['Decimal']['output'];
    taxTotal: MoneyType;
    taxType?: Maybe<Scalars['String']['output']>;
    total: MoneyType;
    totalWithTax: MoneyType;
    trackingNumber?: Maybe<Scalars['String']['output']>;
    trackingUrl?: Maybe<Scalars['String']['output']>;
    vendor?: Maybe<CommonVendor>;
    weight?: Maybe<Scalars['Decimal']['output']>;
    weightUnit?: Maybe<Scalars['String']['output']>;
    width?: Maybe<Scalars['Decimal']['output']>;
};
type OrderShippingMethodType = {
    code: Scalars['String']['output'];
    description?: Maybe<Scalars['String']['output']>;
    id: Scalars['String']['output'];
    isActive: Scalars['Boolean']['output'];
    logoUrl?: Maybe<Scalars['String']['output']>;
    name?: Maybe<Scalars['String']['output']>;
    priority: Scalars['Int']['output'];
    storeId?: Maybe<Scalars['String']['output']>;
    taxType?: Maybe<Scalars['String']['output']>;
    typeName?: Maybe<Scalars['String']['output']>;
};
type OrderTaxDetailType = {
    amount: MoneyType;
    name: Scalars['String']['output'];
    rate: MoneyType;
};
type OrderTotalType = {
    /** Total discount */
    discountTotal: MoneyType;
    /** Is current total in default total currency */
    isDefaultTotalCurrency: Scalars['Boolean']['output'];
    /** Cart subtotal */
    subTotal: MoneyType;
    /** Total tax */
    taxTotal: MoneyType;
    /** Cart total */
    total: MoneyType;
};
type OutlineItemType = {
    id: Scalars['String']['output'];
    name: Scalars['String']['output'];
    /** SEO info */
    seoInfos?: Maybe<Array<SeoInfo>>;
    seoObjectType: Scalars['String']['output'];
};
type OutlineType = {
    /** Outline items */
    items?: Maybe<Array<OutlineItemType>>;
};
/** Information about pagination in a connection. */
type PageInfo = {
    /** When paginating forwards, the cursor to continue. */
    endCursor?: Maybe<Scalars['String']['output']>;
    /** When paginating forwards, are there more items? */
    hasNextPage: Scalars['Boolean']['output'];
    /** When paginating backwards, are there more items? */
    hasPreviousPage: Scalars['Boolean']['output'];
    /** When paginating backwards, the cursor to continue. */
    startCursor?: Maybe<Scalars['String']['output']>;
};
type PaymentInType = {
    authorizedDate?: Maybe<Scalars['DateTime']['output']>;
    billingAddress?: Maybe<OrderAddressType>;
    cancelReason?: Maybe<Scalars['String']['output']>;
    cancelledDate?: Maybe<Scalars['DateTime']['output']>;
    capturedDate?: Maybe<Scalars['DateTime']['output']>;
    comment?: Maybe<Scalars['String']['output']>;
    createdBy?: Maybe<Scalars['String']['output']>;
    createdDate: Scalars['DateTime']['output'];
    currency: CurrencyType;
    customerId: Scalars['String']['output'];
    customerName?: Maybe<Scalars['String']['output']>;
    /** Customer order Payment dynamic property values */
    dynamicProperties: Array<DynamicPropertyValueType>;
    gatewayCode?: Maybe<Scalars['String']['output']>;
    id: Scalars['String']['output'];
    incomingDate?: Maybe<Scalars['DateTime']['output']>;
    isApproved: Scalars['Boolean']['output'];
    isCancelled: Scalars['Boolean']['output'];
    modifiedBy?: Maybe<Scalars['String']['output']>;
    modifiedDate?: Maybe<Scalars['DateTime']['output']>;
    number: Scalars['String']['output'];
    objectType: Scalars['String']['output'];
    operationType: Scalars['String']['output'];
    /** Associated Order */
    order: CustomerOrderType;
    orderId?: Maybe<Scalars['String']['output']>;
    organizationId?: Maybe<Scalars['String']['output']>;
    organizationName?: Maybe<Scalars['String']['output']>;
    outerId?: Maybe<Scalars['String']['output']>;
    parentOperationId?: Maybe<Scalars['String']['output']>;
    paymentMethod?: Maybe<OrderPaymentMethodType>;
    price: MoneyType;
    purpose?: Maybe<Scalars['String']['output']>;
    status?: Maybe<Scalars['String']['output']>;
    statusDisplayValue?: Maybe<Scalars['String']['output']>;
    sum: MoneyType;
    tax: MoneyType;
    transactions: Array<PaymentTransactionType>;
    vendor?: Maybe<CommonVendor>;
    voidedDate?: Maybe<Scalars['DateTime']['output']>;
};
type PaymentTransactionType = {
    amount: MoneyType;
    gatewayIpAddress?: Maybe<Scalars['String']['output']>;
    id: Scalars['String']['output'];
    isProcessed: Scalars['Boolean']['output'];
    note?: Maybe<Scalars['String']['output']>;
    processAttemptCount: Scalars['Int']['output'];
    processError?: Maybe<Scalars['String']['output']>;
    processedDate?: Maybe<Scalars['DateTime']['output']>;
    requestData?: Maybe<Scalars['String']['output']>;
    responseCode?: Maybe<Scalars['String']['output']>;
    responseData?: Maybe<Scalars['String']['output']>;
    status?: Maybe<Scalars['String']['output']>;
    type?: Maybe<Scalars['String']['output']>;
};
type PickupAddressType = {
    /** Address type */
    addressType?: Maybe<Scalars['Int']['output']>;
    /** City */
    city?: Maybe<Scalars['String']['output']>;
    /** Country code */
    countryCode?: Maybe<Scalars['String']['output']>;
    /** Country name */
    countryName?: Maybe<Scalars['String']['output']>;
    /** Description */
    description?: Maybe<Scalars['String']['output']>;
    /** Email */
    email?: Maybe<Scalars['String']['output']>;
    /** Id */
    id: Scalars['String']['output'];
    /** Key */
    key?: Maybe<Scalars['String']['output']>;
    /** Line1 */
    line1?: Maybe<Scalars['String']['output']>;
    /** Line2 */
    line2?: Maybe<Scalars['String']['output']>;
    /** Name */
    name?: Maybe<Scalars['String']['output']>;
    /** Company name */
    organization?: Maybe<Scalars['String']['output']>;
    /** Outer id */
    outerId?: Maybe<Scalars['String']['output']>;
    /** Phone */
    phone?: Maybe<Scalars['String']['output']>;
    /** Postal code */
    postalCode?: Maybe<Scalars['String']['output']>;
    /** Region id */
    regionId?: Maybe<Scalars['String']['output']>;
    /** Region name */
    regionName?: Maybe<Scalars['String']['output']>;
};
type PickupLocationType = {
    /** Address */
    address?: Maybe<PickupAddressType>;
    /** ContactEmail */
    contactEmail?: Maybe<Scalars['String']['output']>;
    /** ContactPhone */
    contactPhone?: Maybe<Scalars['String']['output']>;
    /** Days until ready for pickup */
    deliveryDays?: Maybe<Scalars['Int']['output']>;
    /** Description */
    description?: Maybe<Scalars['String']['output']>;
    /** GeoLocation */
    geoLocation?: Maybe<Scalars['String']['output']>;
    /** Id */
    id: Scalars['String']['output'];
    /** IsActive */
    isActive: Scalars['Boolean']['output'];
    /** Name */
    name: Scalars['String']['output'];
    /** How long an order will be stored at a pickup point */
    storageDays?: Maybe<Scalars['Int']['output']>;
    /** WorkingHours */
    workingHours?: Maybe<Scalars['String']['output']>;
};
type PriceType = {
    /** Actual price */
    actual: MoneyType;
    /** Actual price with tax */
    actualWithTax: MoneyType;
    /** Currency */
    currency: Scalars['String']['output'];
    /** Discount amount */
    discountAmount: MoneyType;
    /** Discount amount with tax */
    discountAmountWithTax: MoneyType;
    discountPercent: Scalars['Decimal']['output'];
    /** Discounts */
    discounts: Array<CatalogDiscountType>;
    /** End date */
    endDate?: Maybe<Scalars['DateTime']['output']>;
    /** Price list */
    list: MoneyType;
    /** Price list with tax */
    listWithTax: MoneyType;
    /** The product min qty */
    minQuantity?: Maybe<Scalars['Int']['output']>;
    /** The product price list */
    pricelistId?: Maybe<Scalars['String']['output']>;
    /** The product price list name */
    pricelistName?: Maybe<Scalars['String']['output']>;
    /** Sale price */
    sale: MoneyType;
    /** Sale price with tax */
    saleWithTax: MoneyType;
    /** Start date */
    startDate?: Maybe<Scalars['DateTime']['output']>;
    /** Tier prices */
    tierPrices: Array<TierPriceType>;
};
/** Products are the sellable goods in an e-commerce project. */
type Product = {
    /** Assets */
    assets: Array<Asset>;
    associations?: Maybe<ProductAssociationConnection>;
    /** Product availability data */
    availabilityData: AvailabilityData;
    brand?: Maybe<BrandType>;
    /** Get brandName for product. */
    brandName?: Maybe<Scalars['String']['output']>;
    /** Breadcrumbs */
    breadcrumbs: Array<Breadcrumb>;
    /** The unique ID of the catalog */
    catalogId?: Maybe<Scalars['String']['output']>;
    category?: Maybe<Category>;
    /** The product SKU. */
    code: Scalars['String']['output'];
    description?: Maybe<DescriptionType>;
    descriptions: Array<DescriptionType>;
    /** Global Trade Item Number (GTIN) */
    gtin?: Maybe<Scalars['String']['output']>;
    hasVariations: Scalars['Boolean']['output'];
    /** Height */
    height?: Maybe<Scalars['Decimal']['output']>;
    /** The unique ID of the product. */
    id: Scalars['String']['output'];
    /** Product images */
    images: Array<ImageType>;
    /** The product main image URL. */
    imgSrc?: Maybe<Scalars['StoreAssetUrl']['output']>;
    /** Product added at least in one wishlist */
    inWishlist: Scalars['Boolean']['output'];
    /** Product is configurable */
    isConfigurable: Scalars['Boolean']['output'];
    /** Product was purchased */
    isPurchased: Scalars['Boolean']['output'];
    keyProperties: Array<Property>;
    /** Length */
    length?: Maybe<Scalars['Decimal']['output']>;
    /** Get points amount */
    loyaltyPoints?: Maybe<MoneyType>;
    /** Manufacturer Part Number (MPN) */
    manufacturerPartNumber?: Maybe<Scalars['String']['output']>;
    masterVariation?: Maybe<VariationType>;
    /** Max. quantity */
    maxQuantity?: Maybe<Scalars['Int']['output']>;
    /** Measure unit */
    measureUnit?: Maybe<Scalars['String']['output']>;
    /** Min. quantity */
    minQuantity?: Maybe<Scalars['Int']['output']>;
    /** Minimum product variation price */
    minVariationPrice?: Maybe<PriceType>;
    /** The name of the product. */
    name: Scalars['String']['output'];
    /** The outer identifier */
    outerId?: Maybe<Scalars['String']['output']>;
    /** All parent categories ids relative to the requested catalog and concatenated with \ . E.g. (1/21/344) */
    outline?: Maybe<Scalars['String']['output']>;
    /** Outlines */
    outlines: Array<OutlineType>;
    /** Defines the number of items in a package. Quantity step for your product's. */
    packSize: Scalars['Int']['output'];
    /** Product price */
    price: PriceType;
    /** Product prices */
    prices: Array<PriceType>;
    /** The type of product */
    productType?: Maybe<Scalars['String']['output']>;
    properties: Array<Property>;
    /** Product rating */
    rating?: Maybe<Rating>;
    /** Product relevance score */
    relevanceScore?: Maybe<Scalars['Float']['output']>;
    /** Request related SEO info */
    seoInfo: SeoInfo;
    /** Request related slug for product */
    slug?: Maybe<Scalars['String']['output']>;
    variations: Array<VariationType>;
    /** Product vendor */
    vendor?: Maybe<CommonVendor>;
    videos?: Maybe<VideoConnection>;
    /** Weight */
    weight?: Maybe<Scalars['Decimal']['output']>;
    /** Weight unit */
    weightUnit?: Maybe<Scalars['String']['output']>;
    /** Width */
    width?: Maybe<Scalars['Decimal']['output']>;
    /** List of wishlist ID with this product */
    wishlistIds: Array<Maybe<Scalars['String']['output']>>;
};
/** product association. */
type ProductAssociation = {
    associatedObjectId?: Maybe<Scalars['String']['output']>;
    associatedObjectType?: Maybe<Scalars['String']['output']>;
    priority: Scalars['Int']['output'];
    product?: Maybe<Product>;
    quantity?: Maybe<Scalars['Int']['output']>;
    tags: Array<Scalars['String']['output']>;
    type: Scalars['String']['output'];
};
/** A connection from an object to a list of objects of type `ProductAssociation`. */
type ProductAssociationConnection = {
    /** A list of all of the edges returned in the connection. */
    edges?: Maybe<Array<Maybe<ProductAssociationEdge>>>;
    /** A list of all of the objects returned in the connection. This is a convenience field provided for quickly exploring the API; rather than querying for "{ edges { node } }" when no edge data is needed, this field can be used instead. Note that when clients like Relay need to fetch the "cursor" field on the edge to enable efficient pagination, this shortcut cannot be used, and the full "{ edges { node } } " version should be used instead. */
    items?: Maybe<Array<Maybe<ProductAssociation>>>;
    /** Information to aid in pagination. */
    pageInfo: PageInfo;
    /** A count of the total number of objects in this connection, ignoring pagination. This allows a client to fetch the first five objects by passing "5" as the argument to `first`, then fetch the total count so it could display "5 of 83", for example. In cases where we employ infinite scrolling or don't have an exact count of entries, this field will return `null`. */
    totalCount?: Maybe<Scalars['Int']['output']>;
};
/** An edge in a connection from an object to another object of type `ProductAssociation`. */
type ProductAssociationEdge = {
    /** A cursor for use in pagination */
    cursor: Scalars['String']['output'];
    /** The item at the end of the edge */
    node?: Maybe<ProductAssociation>;
};
/** Represents promotion object */
type Promotion = {
    /** Promotion description */
    description?: Maybe<Scalars['String']['output']>;
    /** The unique ID of the promotion. */
    id: Scalars['String']['output'];
    /** The name of the promotion */
    name: Scalars['String']['output'];
    /** Promotion type */
    type?: Maybe<Scalars['String']['output']>;
};
/** Products attributes. */
type Property = {
    /** Color code in CSS format. */
    colorCode?: Maybe<Scalars['String']['output']>;
    /** The display order of the property. */
    displayOrder?: Maybe<Scalars['Int']['output']>;
    group?: Maybe<PropertyGroup>;
    /** Is property hidden. */
    hidden: Scalars['Boolean']['output'];
    /** The unique ID of the property. */
    id: Scalars['String']['output'];
    label: Scalars['String']['output'];
    /** Is property has multiple values. */
    multivalue: Scalars['Boolean']['output'];
    /** The name of the property. */
    name: Scalars['String']['output'];
    propertyDictionaryItems?: Maybe<PropertyDictionaryItemConnection>;
    propertyType: PropertyType;
    /** ValueType of the property. */
    propertyValueType: PropertyValueTypes;
    value?: Maybe<Scalars['PropertyValue']['output']>;
    /** The display order of the value. */
    valueDisplayOrder?: Maybe<Scalars['Int']['output']>;
    valueId?: Maybe<Scalars['String']['output']>;
};
/** Represents property dictionary item */
type PropertyDictionaryItem = {
    /** Color code in CSS format. */
    colorCode: Scalars['String']['output'];
    /** The unique ID of the property dictionary item. */
    id: Scalars['String']['output'];
    /** Value order. */
    sortOrder: Scalars['Int']['output'];
    /** Value alias. */
    value?: Maybe<Scalars['String']['output']>;
};
/** A connection from an object to a list of objects of type `PropertyDictionaryItem`. */
type PropertyDictionaryItemConnection = {
    /** A list of all of the edges returned in the connection. */
    edges?: Maybe<Array<Maybe<PropertyDictionaryItemEdge>>>;
    /** A list of all of the objects returned in the connection. This is a convenience field provided for quickly exploring the API; rather than querying for "{ edges { node } }" when no edge data is needed, this field can be used instead. Note that when clients like Relay need to fetch the "cursor" field on the edge to enable efficient pagination, this shortcut cannot be used, and the full "{ edges { node } } " version should be used instead. */
    items?: Maybe<Array<Maybe<PropertyDictionaryItem>>>;
    /** Information to aid in pagination. */
    pageInfo: PageInfo;
    /** A count of the total number of objects in this connection, ignoring pagination. This allows a client to fetch the first five objects by passing "5" as the argument to `first`, then fetch the total count so it could display "5 of 83", for example. In cases where we employ infinite scrolling or don't have an exact count of entries, this field will return `null`. */
    totalCount?: Maybe<Scalars['Int']['output']>;
};
/** An edge in a connection from an object to another object of type `PropertyDictionaryItem`. */
type PropertyDictionaryItemEdge = {
    /** A cursor for use in pagination */
    cursor: Scalars['String']['output'];
    /** The item at the end of the edge */
    node?: Maybe<PropertyDictionaryItem>;
};
/** Property group. */
type PropertyGroup = {
    /** The localized description of the property group. */
    description?: Maybe<Scalars['String']['output']>;
    /** The display order of the property group. */
    displayOrder?: Maybe<Scalars['Int']['output']>;
    /** The unique ID of the property group. */
    id: Scalars['String']['output'];
    /** The localized name of the property group. */
    name?: Maybe<Scalars['String']['output']>;
};
/** The type of catalog property. */
declare enum PropertyType {
    Catalog = "CATALOG",
    Category = "CATEGORY",
    Product = "PRODUCT",
    Variation = "VARIATION"
}
/** The type of catalog property value. */
declare enum PropertyValueTypes {
    Boolean = "BOOLEAN",
    Color = "COLOR",
    DateTime = "DATE_TIME",
    GeoPoint = "GEO_POINT",
    Html = "HTML",
    Integer = "INTEGER",
    LongText = "LONG_TEXT",
    Measure = "MEASURE",
    Number = "NUMBER",
    ShortText = "SHORT_TEXT"
}
type Rating = {
    /** Total count of customer reviews */
    reviewCount: Scalars['Int']['output'];
    /** Average rating */
    value: Scalars['Decimal']['output'];
};
type SeoInfo = {
    id: Scalars['String']['output'];
    imageAltDescription?: Maybe<Scalars['String']['output']>;
    isActive: Scalars['Boolean']['output'];
    languageCode?: Maybe<Scalars['String']['output']>;
    metaDescription?: Maybe<Scalars['String']['output']>;
    metaKeywords?: Maybe<Scalars['String']['output']>;
    name?: Maybe<Scalars['String']['output']>;
    objectId: Scalars['String']['output'];
    objectType: Scalars['String']['output'];
    outline?: Maybe<Scalars['String']['output']>;
    pageTitle?: Maybe<Scalars['String']['output']>;
    semanticUrl: Scalars['String']['output'];
    storeId?: Maybe<Scalars['String']['output']>;
};
type TierPriceType = {
    /** Price */
    price: MoneyType;
    /** Price with tax */
    priceWithTax: MoneyType;
    /** Quantity */
    quantity: Scalars['Long']['output'];
};
type VariationType = {
    /** Assets */
    assets: Array<Asset>;
    associations?: Maybe<ProductAssociationConnection>;
    /** Availability data */
    availabilityData: AvailabilityData;
    /** SKU of variation. */
    code: Scalars['String']['output'];
    /** Id of variation. */
    id: Scalars['String']['output'];
    /** Product images */
    images: Array<ImageType>;
    /** Max. quantity. */
    maxQuantity?: Maybe<Scalars['Int']['output']>;
    /** Min. quantity. */
    minQuantity?: Maybe<Scalars['Int']['output']>;
    /** Name of variation. */
    name: Scalars['String']['output'];
    /** Outlines */
    outlines?: Maybe<Array<OutlineType>>;
    /** Defines the number of items in a package. Quantity step for your product's. */
    packSize?: Maybe<Scalars['Int']['output']>;
    /** Product price */
    price: PriceType;
    /** Product prices */
    prices: Array<PriceType>;
    /** The type of product */
    productType?: Maybe<Scalars['String']['output']>;
    properties: Array<Property>;
    /** Product rating */
    rating?: Maybe<Rating>;
    /** Request related slug for product */
    slug?: Maybe<Scalars['String']['output']>;
    /** Product vendor */
    vendor?: Maybe<CommonVendor>;
};
/** A connection from an object to a list of objects of type `Video`. */
type VideoConnection = {
    /** A list of all of the edges returned in the connection. */
    edges?: Maybe<Array<Maybe<VideoEdge>>>;
    /** A list of all of the objects returned in the connection. This is a convenience field provided for quickly exploring the API; rather than querying for "{ edges { node } }" when no edge data is needed, this field can be used instead. Note that when clients like Relay need to fetch the "cursor" field on the edge to enable efficient pagination, this shortcut cannot be used, and the full "{ edges { node } } " version should be used instead. */
    items?: Maybe<Array<Maybe<VideoType>>>;
    /** Information to aid in pagination. */
    pageInfo: PageInfo;
    /** A count of the total number of objects in this connection, ignoring pagination. This allows a client to fetch the first five objects by passing "5" as the argument to `first`, then fetch the total count so it could display "5 of 83", for example. In cases where we employ infinite scrolling or don't have an exact count of entries, this field will return `null`. */
    totalCount?: Maybe<Scalars['Int']['output']>;
};
/** An edge in a connection from an object to another object of type `Video`. */
type VideoEdge = {
    /** A cursor for use in pagination */
    cursor: Scalars['String']['output'];
    /** The item at the end of the edge */
    node?: Maybe<VideoType>;
};
type VideoType = {
    /** Video URL */
    contentUrl: Scalars['String']['output'];
    /** Culture name */
    cultureName?: Maybe<Scalars['String']['output']>;
    /** Video description */
    description: Scalars['String']['output'];
    /** Video duration */
    duration?: Maybe<Scalars['String']['output']>;
    /** Embedded video URL */
    embedUrl?: Maybe<Scalars['String']['output']>;
    /** Video name */
    name: Scalars['String']['output'];
    /** ID of the object video is attached to */
    ownerId: Scalars['String']['output'];
    /** Type of the object video is attached to (Product, Category) */
    ownerType: Scalars['String']['output'];
    /** Sort order */
    sortOrder: Scalars['Int']['output'];
    /** Video thumbnail URL */
    thumbnailUrl: Scalars['String']['output'];
    /** Video upload date */
    uploadDate?: Maybe<Scalars['DateTime']['output']>;
};

interface IProps$1 {
    color?: VcButtonColorType;
    size?: VcButtonSizeType;
    variant?: VcButtonVariantType;
    type?: VcButtonTypeType;
    disabled?: boolean;
    loading?: boolean;
    to?: RouteLocationRaw | null;
    externalLink?: string;
    target?: "_self" | "_blank";
    prependIcon?: string;
    appendIcon?: string;
    icon?: boolean | string;
    title?: string;
    ariaLabel?: string;
    truncate?: boolean;
    fullWidth?: boolean;
    noWrap?: boolean;
    minWidth?: string;
    tag?: string;
    iconSize?: string;
    square?: boolean;
    tabindex?: string | number;
}
declare function focus(): void;
declare function blur(): void;
declare var __VLS_16: {};
declare var __VLS_23: {};
declare var __VLS_25: {};
declare var __VLS_32: {};
type __VLS_Slots$1 = {} & {
    prepend?: (props: typeof __VLS_16) => any;
} & {
    default?: (props: typeof __VLS_23) => any;
} & {
    append?: (props: typeof __VLS_25) => any;
} & {
    loader?: (props: typeof __VLS_32) => any;
};
declare const __VLS_base$1: vue.DefineComponent<IProps$1, {
    focus: typeof focus;
    blur: typeof blur;
    el: vue.ComputedRef<HTMLElement | null>;
}, {}, {}, {}, vue.ComponentOptionsMixin, vue.ComponentOptionsMixin, {} & {
    click: (value: MouseEvent) => any;
}, string, vue.PublicProps, Readonly<IProps$1> & Readonly<{
    onClick?: ((value: MouseEvent) => any) | undefined;
}>, {
    type: VcButtonTypeType;
    to: RouteLocationRaw | null;
    variant: VcButtonVariantType;
    loading: boolean;
    tag: string;
    truncate: boolean;
    color: VcButtonColorType;
    disabled: boolean;
    tabindex: string | number;
    noWrap: boolean;
    fullWidth: boolean;
}, {}, {}, {}, string, vue.ComponentProvideOptions, false, {}, any>;
declare const __VLS_export$1: __VLS_WithSlots$1<typeof __VLS_base$1, __VLS_Slots$1>;
declare const _default$1: typeof __VLS_export$1;

type __VLS_WithSlots$1<T, S> = T & {
    new (): {
        $slots: S;
    };
};

type ExtendedMenuLinkType = {
    id?: string;
    title?: string;
    icon?: string;
    route?: RouteLocationRaw;
    children?: ExtendedMenuLinkType[];
    priority?: number;
    isCatalogItem?: boolean;
    dataTestId?: string;
};

interface IProps {
    title?: string;
    prependIcon?: string;
    appendIcon?: string;
    collapsible?: boolean;
    collapsed?: boolean;
    shadow?: boolean;
    border?: boolean;
    size?: "xs" | "sm" | "md" | "lg";
}
declare var __VLS_9: {
    collapsible: boolean;
    collapsed: boolean;
};
declare var __VLS_11: {
    collapsible: boolean;
    collapsed: boolean;
};
declare var __VLS_13: {};
declare var __VLS_20: {};
declare var __VLS_22: {
    collapsible: boolean;
    collapsed: boolean;
};
declare var __VLS_34: {};
declare var __VLS_36: {};
declare var __VLS_38: {};
declare var __VLS_40: {};
type __VLS_Slots = {} & {
    'header-container'?: (props: typeof __VLS_9) => any;
} & {
    header?: (props: typeof __VLS_11) => any;
} & {
    prepend?: (props: typeof __VLS_13) => any;
} & {
    title?: (props: typeof __VLS_20) => any;
} & {
    append?: (props: typeof __VLS_22) => any;
} & {
    'default-container'?: (props: typeof __VLS_34) => any;
} & {
    default?: (props: typeof __VLS_36) => any;
} & {
    'footer-container'?: (props: typeof __VLS_38) => any;
} & {
    footer?: (props: typeof __VLS_40) => any;
};
declare const __VLS_base: vue.DefineComponent<IProps, {}, {}, {}, {}, vue.ComponentOptionsMixin, vue.ComponentOptionsMixin, {} & {
    toggleCollapse: (value: boolean) => any;
}, string, vue.PublicProps, Readonly<IProps> & Readonly<{
    onToggleCollapse?: ((value: boolean) => any) | undefined;
}>, {
    size: "xs" | "sm" | "md" | "lg";
    shadow: boolean;
    border: boolean;
}, {}, {}, {}, string, vue.ComponentProvideOptions, false, {}, any>;
declare const __VLS_export: __VLS_WithSlots<typeof __VLS_base, __VLS_Slots>;
declare const _default: typeof __VLS_export;

type __VLS_WithSlots<T, S> = T & {
    new (): {
        $slots: S;
    };
};

type ExtensionEntryType<Props = never, Condition extends (parameter: any) => boolean = never> = {
    component: Component;
    condition?: Condition;
    props?: Props;
};
/**
 * Here we define the extension categories and the extension entries for each category.
 * ExtensionEntryType<Props, Condition> is a type that defines the extension entry for a given category.
 */
type ExtensionCategoryMapType = {
    headerMenu: ExtensionEntryType<{
        item: ExtendedMenuLinkType;
    }>;
    mobileMenu: ExtensionEntryType<{
        item: ExtendedMenuLinkType;
    }>;
    accountMenu: ExtensionEntryType<{
        item: ExtendedMenuLinkType;
    }>;
    mobileHeader: ExtensionEntryType;
    productCard: ExtensionEntryType<{
        product?: Product;
        isTextShown?: boolean;
        lazy?: boolean;
    }, (product: Product) => boolean>;
    productPage: ExtensionEntryType<{
        product?: Product;
    }, (product: Product) => boolean>;
    paymentPage: ExtensionEntryType<{
        order: CustomerOrderType;
        paymentTypeName: string;
    }, ({ order, paymentTypeName }: {
        order: CustomerOrderType;
        paymentTypeName: string;
    }) => boolean>;
    orderPaymentPage: ExtensionEntryType<{
        order: CustomerOrderType;
        paymentTypeName: string;
    }, ({ order, paymentTypeName }: {
        order: CustomerOrderType;
        paymentTypeName: string;
    }) => boolean>;
};

type ExtensionRegistryStateType = {
    [K in keyof ExtensionCategoryMapType]: Record<string, ExtensionCategoryMapType[K]>;
};
type ExtensionCategoryType = keyof ExtensionCategoryMapType;

declare function _useExtensionRegistry(): {
    entries: vue.ShallowRef<ExtensionRegistryStateType, ExtensionRegistryStateType>;
    register: <C extends ExtensionCategoryType, N extends string>(category: C, name: N, item: ExtensionRegistryStateType[C][N]) => void;
    unregister: <C extends ExtensionCategoryType>(category: C, name: string) => void;
    getComponent: <C extends ExtensionCategoryType, N extends keyof ExtensionRegistryStateType[C]>(category: C, name: N) => vue.Component;
    getEntries: <C extends ExtensionCategoryType>(category: C, names?: string[]) => Readonly<Pick<ExtensionRegistryStateType[C], string>> | Readonly<ExtensionRegistryStateType[C]>;
    getProps: <C extends ExtensionCategoryType, N extends keyof ExtensionRegistryStateType[C]>(category: C, name: N) => ExtensionRegistryStateType[C][N]["props"];
    isRegistered: <C extends ExtensionCategoryType, N extends keyof ExtensionRegistryStateType[C]>(category: C, name: N) => boolean;
    canRender: <C extends ExtensionCategoryType, N extends keyof ExtensionRegistryStateType[C]>(category: C, name: N, parameter: NonNullable<ExtensionRegistryStateType[C][N]["condition"]> extends (arg: infer P) => boolean ? P : unknown) => boolean;
};
declare const useExtensionRegistry: typeof _useExtensionRegistry;

/**
 * Non-cached version of Apollo Client
 */
declare const graphqlClient: ApolloClient<_apollo_client_cache.NormalizedCacheObject>;
/**
 * Default (cached) version of Apollo Client
 */
declare const apolloClient: ApolloClient<_apollo_client_cache.NormalizedCacheObject>;

declare const useModuleSettings: _vueuse_core.UseMemoizeReturn<{
    getModuleSettings: <T extends Record<string, string>>(settingsMapping: T) => { [K in T[keyof T]]?: string | number | boolean | null | undefined; };
    getSettingValue: (name: string) => string | number | boolean | null | undefined;
    hasModuleSettings: vue.ComputedRef<boolean>;
    isEnabled: (key: string) => boolean;
    moduleSettings: vue.ComputedRef<{
        name: string;
        value?: string | number | boolean | null;
    }[] | undefined>;
}, [moduleId: string]>;

declare function createI18n(locale: string, currency: string, fallback?: {
    locale: string;
    message: LocaleMessage;
}, pluralRuleLocales?: string[]): vue_i18n.I18n<{}, {
    en: {
        short: {
            year: "numeric";
            month: "short";
            day: "numeric";
        };
        long: {
            year: "numeric";
            month: "short";
            day: "numeric";
            hour: "numeric";
            minute: "numeric";
            second: "numeric";
        };
    };
    de: {
        short: {
            year: "numeric";
            month: "short";
            day: "numeric";
        };
        long: {
            year: "numeric";
            month: "short";
            day: "numeric";
            hour: "numeric";
            minute: "numeric";
            second: "numeric";
        };
    };
}, {
    [x: string]: IntlNumberFormat;
}, string, false>;
type I18n = ReturnType<typeof createI18n>;

type GlobalVariablesType = {
    storeId?: string;
    catalogId?: string;
    userId?: string;
    userName?: string;
    organizationId?: string;
    cultureName?: string;
    currencyCode?: string;
    i18n?: I18n;
    router?: Router;
};
declare const globals: Readonly<Required<GlobalVariablesType>>;

/**
 * `@vc-frontend/core` — the curated PUBLIC surface a Module Federation plugin may
 * import from the host. A facade: re-exports host code, nothing moves.
 * Publish-from-source: plugins consume TYPES only (compiled contract/index.d.ts); the
 * host provides the live instance at runtime via the MF shared singleton.
 * Keep it SMALL and additive — removing/renaming an export breaks every plugin.
 */

/** Contract version, single-sourced from core-api/package.json (managed by build:core-types / bump:core). */
declare const CORE_VERSION: string;

export { CORE_VERSION, _default$1 as VcButton, _default$2 as VcMarkdownRender, _default as VcWidget, apolloClient, globals, graphqlClient, useExtensionRegistry, useModuleSettings };
export type { I18n };
