/**
 * Publish-from-source type build for `@vc-frontend/core` (VCST-5159, #3). Produces a
 * single self-contained `dist/index.d.ts` a plugin type-checks against without reaching
 * into host source. Two steps: vue-tsc emits the facade's type graph, then
 * rollup-plugin-dts inlines it into one file (only shared peer imports remain).
 * Run `yarn build:core-types` after any facade change; output is committed.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { rollup } from "rollup";
import dts from "rollup-plugin-dts";

const CORE_API_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(CORE_API_DIR, "../..");
// Resolve vue-tsc's bin to an absolute path and run it with the current Node binary
// (process.execPath) — never via PATH-resolved `npx`, which a hostile PATH could hijack.
const require = createRequire(import.meta.url);
const VUE_TSC_BIN = resolve(dirname(require.resolve("vue-tsc/package.json")), "bin/vue-tsc.js");
const EMIT_DIR = resolve(CORE_API_DIR, ".types-build");
const DIST_DIR = resolve(CORE_API_DIR, "dist");
const EMIT_ENTRY = resolve(EMIT_DIR, "core-api/index.d.ts");
const OUT_FILE = resolve(DIST_DIR, "index.d.ts");

const BANNER = `// AUTO-GENERATED by client-app/core-api/build-types.mjs — DO NOT EDIT.
// Self-contained public type contract of @vc-frontend/core (VCST-5159).
// Regenerate with: yarn build:core-types
`;

function step(msg) {
  console.log(`[build-types] ${msg}`);
}

// 1 ── emit the facade's declaration graph ────────────────────────────────────
step("emitting declarations with vue-tsc…");
rmSync(EMIT_DIR, { recursive: true, force: true });
const emit = spawnSync(process.execPath, [VUE_TSC_BIN, "--project", resolve(CORE_API_DIR, "tsconfig.types.json")], {
  cwd: REPO_ROOT,
  encoding: "utf8",
});
// vue-tsc reports diagnostics in host files that are outside the facade surface
// (e.g. ui-kit components relying on ambient globals we don't load here). Those
// files never reach the rolled-up contract, so the emit is validated by its
// OUTPUT, not by exit code — declarations are still written (noEmitOnError:false).
if (!existsSync(EMIT_ENTRY)) {
  console.error(`[build-types] FAILED: no declarations emitted at ${EMIT_ENTRY} (vue-tsc exit ${emit.status}).`);
  console.error((emit.stdout ?? "") + (emit.stderr ?? ""));
  process.exit(1);
}

// 2 ── roll the graph up into one self-contained file ─────────────────────────
step("bundling into a single self-contained index.d.ts…");
const bundle = await rollup({
  input: EMIT_ENTRY,
  // Unresolved imports here are the shared peer packages (vue, @apollo/client, …) —
  // intentionally kept external; silence the expected noise.
  onwarn: () => {},
  plugins: [
    dts({
      respectExternal: false,
      compilerOptions: { baseUrl: EMIT_DIR, paths: { "@/*": [`${EMIT_DIR}/*`] } },
    }),
  ],
});
const { output } = await bundle.generate({ format: "es" });
await bundle.close();

let code = output[0].code;

// Guard: the whole point is zero host coupling. If any `@/…` survived, the rollup
// failed to inline something — fail loudly rather than ship a broken contract.
if (code.includes("@/")) {
  console.error("[build-types] FAILED: unresolved '@/' reference(s) remain in the rolled contract.");
  process.exit(1);
}

mkdirSync(DIST_DIR, { recursive: true });
writeFileSync(OUT_FILE, BANNER + "\n" + code, "utf8");
rmSync(EMIT_DIR, { recursive: true, force: true });

// External peer imports the contract expects the plugin (or host) to provide.
const externals = [...new Set([...code.matchAll(/from ['"]([^'".][^'"]*)['"]/g)].map((m) => m[1]))].sort((a, b) =>
  a.localeCompare(b),
);
step(`wrote ${OUT_FILE} (${code.split("\n").length} lines).`);
step(`external peer imports: ${externals.join(", ") || "(none)"}`);
