# v1.0.0.vst
name: Release hotfix

on:
  workflow_dispatch:

jobs:
  build-theme:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
    steps:

    - name: Install VirtoCommerce.GlobalTool
      uses: VirtoCommerce/vc-github-actions/setup-vcbuild@master

    - uses: actions/checkout@v2
      with:
            fetch-depth: 0

    - name: Get Artifact Version
      uses: VirtoCommerce/vc-github-actions/get-image-version@master
      id: artifactVer

    - name: Get changelog
      id: changelog
      uses: VirtoCommerce/vc-github-actions/changelog-generator@master

    - name: Build
      id: build
      uses: VirtoCommerce/vc-github-actions/build-vue-theme@master

    - name: Create Release
      if: ${{ github.ref == 'refs/heads/master' }}
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.artifactVer.outputs.prefix }}
        release_name: ${{ steps.artifactVer.outputs.prefix }}
        draft: false
        prerelease: false
        body: ${{ steps.changelog.outputs.changelog }}

    - name: Upload Release Asset
      if: ${{ github.ref == 'refs/heads/master' }}
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.build.outputs.artifactPath }}
        asset_name: ${{ steps.build.outputs.artifactName }}
        asset_content_type: application/zip
