name: Theme Release Hotfix
on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      BLOB_SAS: ${{ secrets.BLOB_TOKEN }}
      VERSION_SUFFIX: ""

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Set up Node 22
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '22'

      - name: Enable corepack
        run: |
          corepack enable

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@911ef81b14b267a261d70ac94e43d3c822a709d5 # v10

      - name: Install VirtoCommerce.GlobalTool
        uses: VirtoCommerce/vc-github-actions/setup-vcbuild@master

      - name: Setup Git Credentials
        uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
        with:
          githubToken: ${{ secrets.REPO_TOKEN }}

      - name: Get Image Version
        uses: VirtoCommerce/vc-github-actions/get-image-version@master
        id: image
        with:
          projectType: "theme"

      - name: Set VERSION_SUFFIX variable
        run: |
          echo "VERSION_SUFFIX=${{ steps.image.outputs.suffix }}" >> $GITHUB_ENV

      - name: Set VERSION
        run: |
          echo "VERSION=${{ steps.image.outputs.prefix }}" >> $GITHUB_ENV

      - name: Update package.json Version
        run: |
          yarn version ${{ env.VERSION }}

      - name: Install dependencies
        run: |
          yarn install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: |
          yarn build

      - name: Unit Tests
        run: |
          yarn test:unit --run

      - name: Typing Tests
        run: |
          yarn test:typing --run

      - name: Add files to zip
        run: |
          mkdir -p ./tmp/default
          mkdir ./artifacts
          mv ./dist/* ./tmp/default
          cd ./tmp
          # zip -r ../artifacts/$(jq -r .name ../package.json)-$(jq -r .version ../package.json).zip ./default
          zip -r ../artifacts/${GITHUB_REPOSITORY#*/}-${{ steps.image.outputs.prefix }}.zip ./default

      - name: Publish to Blob
        id: blobRelease
        uses: VirtoCommerce/vc-github-actions/publish-blob-release@master
        with:
          blobSAS: ${{ secrets.BLOB_TOKEN }}

      - name: Create GH Release
        env:
          IMAGE_PREFIX: ${{ steps.image.outputs.prefix }}
        run: |
          gh release create "$IMAGE_PREFIX" \
                --target="$GITHUB_REF_NAME" \
                --latest=false \
                --repo="$GITHUB_REPOSITORY" \
                --title="$IMAGE_PREFIX" \
                "./artifacts/${GITHUB_REPOSITORY#*/}-${IMAGE_PREFIX}.zip#${GITHUB_REPOSITORY#*/}-${IMAGE_PREFIX}.zip"
